export const hotels = [
  {
    id: 1,
    name: 'Hotel Paseo del Arte',
    place: 'Madrid',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 24,
    photo: 'https://image.freepik.com/foto-gratis/pequeno-interior-habitacion-hotel-cama-doble-bano_1262-12489.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 2,
    name: 'Hotel Mediodía',
    place: 'Madrid',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 37,
    photo: 'https://image.freepik.com/foto-gratis/tipo-complejo-entretenimiento-popular-complejo-piscinas-parques-acuaticos-turquia-mas-5-millones-visitantes-al-ano-amara-dolce-vita-hotel-lujo-recurso-tekirova-kemer_146671-18728.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 3,
    name: 'AC Hotel',
    place: 'Madrid',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 23,
    photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 4,
    name: 'El Hostal',
    place: 'Madrid',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 67,
    photo: 'https://image.freepik.com/foto-gratis/tipo-complejo-entretenimiento-popular-complejo-piscinas-parques-acuaticos-turquia-mas-5-millones-visitantes-al-ano-amara-dolce-vita-hotel-lujo-recurso-tekirova-kemer_146671-18728.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 5,
    name: 'Hotel Madrid Alameda',
    place: 'Madrid',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 49,
    photo: 'https://image.freepik.com/foto-gratis/pequeno-interior-habitacion-hotel-cama-doble-bano_1262-12489.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 6,
    name: 'Hotel Le Petit Paris',
    place: 'Sevilla',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 94,
    photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    banner: 'https://image.freepik.com/foto-gratis/pequeno-interior-habitacion-hotel-cama-doble-bano_1262-12489.jpg'
  },
  {
    id: 7,
    name: 'Hotel Puerta Real',
    place: 'Sevilla',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 98,
    photo: 'https://image.freepik.com/foto-gratis/tipo-complejo-entretenimiento-popular-complejo-piscinas-parques-acuaticos-turquia-mas-5-millones-visitantes-al-ano-amara-dolce-vita-hotel-lujo-recurso-tekirova-kemer_146671-18728.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 8,
    name: 'Hotel Málaga Centro',
    place: 'Málaga',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 87,
    photo: 'https://image.freepik.com/foto-gratis/edificio-condominios-residenciales-8-pisos-piscina-medio-edificio_37282-895.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 9,
    name: 'Hotel La Casa Mata Central',
    place: 'Málaga',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 51,
    photo: 'https://image.freepik.com/foto-gratis/tipo-complejo-entretenimiento-popular-complejo-piscinas-parques-acuaticos-turquia-mas-5-millones-visitantes-al-ano-amara-dolce-vita-hotel-lujo-recurso-tekirova-kemer_146671-18728.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 10,
    name: 'Hotel Niza',
    place: 'San Sebastián',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 65,
    photo: 'https://image.freepik.com/foto-gratis/pequeno-interior-habitacion-hotel-cama-doble-bano_1262-12489.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 11,
    name: 'Hotel Monte Ulia',
    place: 'San Sebastián',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 65,
    photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 12,
    name: 'Hotel Maycar',
    place: 'Coruña',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 65,
    photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 13,
    name: 'Hotel Nido',
    place: 'Coruña',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 65,
    photo: 'https://image.freepik.com/foto-gratis/pequeno-interior-habitacion-hotel-cama-doble-bano_1262-12489.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 14,
    name: 'Hotel Castilla',
    place: 'Albacete',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 65,
    photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  {
    id: 15,
    name: 'Hotel Albacete',
    place: 'Albacete',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    phone: 65,
    photo: 'https://image.freepik.com/foto-gratis/tipo-complejo-entretenimiento-popular-complejo-piscinas-parques-acuaticos-turquia-mas-5-millones-visitantes-al-ano-amara-dolce-vita-hotel-lujo-recurso-tekirova-kemer_146671-18728.jpg',
    banner: 'https://image.freepik.com/foto-gratis/cierrese-arriba-taza-cafe-agradable-gemela-cama-blanca-habitacion-concepto-bien-viaje-vacaciones-hospitalidad-hotel_1150-13594.jpg'
  },
  
]

export const trending = [
    {
      id: 1,
      name: 'Mallorca',
      photo: 'https://image.freepik.com/foto-gratis/pequeno-interior-habitacion-hotel-cama-doble-bano_1262-12489.jpg',
    },
    {
      id: 2,
      name: 'Málaga',
      photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    },
    {
      id: 3,
      name: 'Madrid',
      photo: 'https://image.freepik.com/foto-gratis/tipo-complejo-entretenimiento-popular-complejo-piscinas-parques-acuaticos-turquia-mas-5-millones-visitantes-al-ano-amara-dolce-vita-hotel-lujo-recurso-tekirova-kemer_146671-18728.jpg',
    },
    {
      id: 4,
      name: 'Valencia',
      photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    },
    {
      id: 5,
      name: 'Costa Brava',
      photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    },
    {
      id: 6,
      name: 'Granada',
      photo: 'https://image.freepik.com/foto-gratis/hamacas-palmeras_1203-201.jpg',
    },
];

export const golfs = [
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:00:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:00:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:10:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:10:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:20:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:20:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:30:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:30:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:40:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:40:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:50:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T07:50:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:00:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:00:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:10:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:10:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:20:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:20:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:30:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:30:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:40:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:40:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:50:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T08:50:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:00:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:00:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:10:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:10:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:20:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:20:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:30:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:30:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:40:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:40:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:50:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T09:50:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:00:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:00:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:10:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:10:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:20:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:20:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    {
        "description": null,
        "duration": 10,
        "icon": null,
        "id": 27,
        "idChannel": null,
        "idResource": 1,
        "idType": 27,
        "max": 4,
        "maxFilter": null,
        "min": 1,
        "minFilter": null,
        "multiple": null,
        "name": "LC 1GF 18 Course A",
        "onlineClientType": 1,
        "onlyPackage": false,
        "price": 10,
        "priceName": null,
        "rack": 110,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:30:00+02:00",
        "tags": [
            "18holes"
        ]
    },
    {
        "description": "Precio por persona | Mín. 2 Jugadores",
        "duration": 10,
        "icon": null,
        "id": 33,
        "idChannel": null,
        "idResource": 1,
        "idType": 33,
        "max": 4,
        "maxFilter": 4,
        "min": 2,
        "minFilter": 2,
        "multiple": 2,
        "name": "GF 18 + buggy desglosado COURSE A",
        "onlineClientType": null,
        "onlyPackage": false,
        "price": 120,
        "priceName": null,
        "rack": 120,
        "requiresTag": false,
        "resourceName": "Tee 1",
        "resourceTags": [],
        "start": "2021-10-21T10:30:00+02:00",
        "tags": [
            "18holes",
            "buggy"
        ]
    },
    
]; 